version: 2.1
jobs:
    build:
        docker:
            - image: debian
        resource_class: arm.large
        steps:
            - checkout
            - setup_remote_docker
            - run: ./build.sh
