version: 2.1
jobs:
    build:
        docker:
            - image: cimg/base:current
        resource_class: arm.large
        steps:
            - checkout
            - setup_remote_docker
            - run:
                  name: Build Firmware
                  command: ./build-firmware.sh
            - run:
                  name: Build Protect
                  command: ./build-protect.sh
