name: Docker Image Build CI

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      shell: bash
      run: echo "$SHELL" && ./build.sh
